fn main() raises:
    try:
        print('open file'):
    except:
        raise Error('Error 404'):
    finally:
        print('file closed')